module.exports = {
    APP_PORT: process.env.TNUKE_PORT,
    CONSUMER_KEY: process.env.TNUKE_CONSUMER_KEY,
	CONSUMER_SECRET: process.env.TNUKE_CONSUMER_SECRET,
	CALLBACK_URL: process.env.TNUKE_CALLBACK_URL,
	SESSION_SECRET: process.env.TNUKE_SESSION_SECRET
};